version: '3.8'

services:
  db:
    image: postgres:12-alpine@sha256:002161f3f4472b37e6014e7d5136a81076ebec5add084a2cd433cf84a416bb11
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
    volumes:
      - postgres-db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    environment:
      APP_FRONTEND_PORT: '8080'
      DB_PORT: '5433'
      DB_HOST: 'db'
    ports:
      - '8080:8080'
    depends_on:
      - 'db'
volumes:
  postgres-db:
